version: '3'
services:
  dns:
    build: .
    volumes:
      - ./named.conf:/etc/bind/named.conf
      - ./db.douglas.aluno.ic.ufmt.br:/etc/bind/zones/db.douglas.aluno.ic.ufmt.br
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: always