version: '3'
services:
  ftp-server:
    image: fauria/vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - ./data/:/home/vsftpd
    environment:
      - FTP_USER=strappasson
      - FTP_PASS=123456
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
      - LOCAL_UMASK=777
    networks:
      - ftp-network
  

  nginx-server:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./data/strappasson:/usr/share/nginx/html
    depends_on:
      - ftp-server
    restart: always
    networks:
      - ftp-network  

networks:
  ftp-network:
    driver: bridge
